{
    'name': 'TD Jaugeage et Décompte',
    'version': '18.0.1.0',
    'category': 'Inventory',
    'summary': 'Gestion complète des rotations, pompes, cuves et réconciliation financière',
    'description': 'Ce module permet de gérer les ventes de carburants, les stocks de cuves et le décompte financier journalier.',
    'author': 'Transition Digitale',
    'website': 'https://transitiondigitale.tech',
    'depends': ['base', 'product', 'hr'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/gauging_views.xml',
        'reports/gauging_reports.xml',
        'reports/gauging_report_templates.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}